name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Features to be tested. e.g. footer,header'
        required: false
        default: ""
        type: string
      suite:
        description: 'Test suite to be used. e.g. regression/smoke'
        required: true
        type: choice
        default: "smoke"
        options:
           - smoke
           - regression
      browser:
        description: 'Browser to be used. e.g. chromium/firefox/webkit'
        required: false
        type: choice
        default: ""
        options:
           - chromium
           - firefox
           - webkit

jobs:
  test:
    name: Playwright tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node 
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Display inputs
      run: | 
        echo "Feature: ${{ inputs.feature }}"
        echo "Test suite: ${{ inputs.suite }}"
        echo "Browser: ${{ inputs.browser }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "RunID: ${{ github.run_id }}"
    
    - name: Run ${{ inputs.feature }} tests from ${{ inputs.suite }} test suite on ${{ inputs.browser }}
      run: npx playwright test tests/${{ inputs.feature }} --project=${{ inputs.browser }} --grep @${{ inputs.suite }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: report-${{ inputs.suite }}-${{ inputs.browser }}-${{ steps.date.outputs.date }}
        path: playwright-report/
        retention-days: 2
