name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Features to be tested. e.g. footer,header'
        required: false
        default: ""
        type: string
      suite:
        description: 'Test suite to be used. e.g. regression/smoke'
        required: true
        type: choice
        default: "smoke"
        options:
           - smoke
           - regression
      browser:
        description: 'Browser to be used. e.g. chromium/firefox/webkit'
        required: false
        type: choice
        default: ""
        options:
           - chromium
           - firefox
           - webkit

jobs:
  setup:
    name: Setup
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Node Packages
      run: |
        npm cache clean --force
        npm i
        npm list --depth=0 --silent

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Display inputs
      run: | 
        echo "Feature: ${{ inputs.feature }}"
        echo "Test suite: ${{ inputs.suite }}"
        echo "Browser: ${{ inputs.browser }}"
    
    - name: Run ${{ inputs.feature }} tests from ${{ inputs.suite }} test suite
      run: npx playwright test tests/${{ inputs.feature }} --project=${{ inputs.browser }} --grep @${{ inputs.suite }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 2
